101-lazy_matrix_mul.txt

>>> lazy_matrix_mul = __import__('101-lazy_matrix_mul').lazy_matrix_mul

#Correct values
>>> print(lazy_matrix_mul([[1, 2], [3, 4]], [[1, 2], [3, 4]]))
[[ 7 10]
 [15 22]]

>>> print(lazy_matrix_mul([[1, 2]], [[3, 4], [5, 6]]))
[[13 16]]

>>> print(lazy_matrix_mul([[1.5, 2.5]], [[3.5, 4.5], [5.5, 6.5]]))
[[19. 23.]]


#Bad values
>>> print(lazy_matrix_mul([[1, 2]], [[1, 2]]))
Traceback (most recent call last):
ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

>>> print(lazy_matrix_mul([], [[1, 2]]))
Traceback (most recent call last):
ValueError: shapes (1,0) and (2,2) not aligned: 0 (dim 1) != 2 (dim 0)

>>> print(lazy_matrix_mul([[1, 2]], [[]]))
Traceback (most recent call last):
ValueError: shapes (2,2) and (1,0) not aligned: 2 (dim 1) != 1 (dim 0)

>>> print(lazy_matrix_mul([[]], []))
Traceback (most recent call last):
ValueError: shapes (1,0) and (2,2) not aligned: 0 (dim 1) != 2 (dim 0)

>>> print(lazy_matrix_mul("not", [[1, 2]]))
Traceback (most recent call last):
TypeError: Scalar operands are not allowed, use '*' instead

>>> print(lazy_matrix_mul([[1, 2]], "not"))
Traceback (most recent call last):
TypeError: Scalar operands are not allowed, use '*' instead


>>> print(lazy_matrix_mul([1], [[2, 3]]))
Traceback (most recent call last):
TypeError: m_a must be a list of lists

>>> print(lazy_matrix_mul([[1, 2]], [3]))
Traceback (most recent call last):
TypeError: m_b must be a list of lists

>>> print(lazy_matrix_mul([[1, "not"]], [[3, 4]]))
Traceback (most recent call last):
TypeError: invalid data type for einsum

>>> print(lazy_matrix_mul([[1, 2]], [[3, "not"]]))
Traceback (most recent call last):
TypeError: invalid data type for einsum

>>> print(lazy_matrix_mul([[1], [2, 3]], [[1, 2], [3, 4]]))
Traceback (most recent call last):
TypeError: setting an array element with a sequence.

>>> print(lazy_matrix_mul([[1, 2], [2, 3]], [[1], [3, 4]]))
Traceback (most recent call last):
TypeError: setting an array element with a sequence.


#Empty
>>> print(lazy_matrix_mul())
Traceback (most recent call last):
TypeError: lazy_matrix_mul() missing 2 required positional arguments: 'm_a' and 'm_b'
